name: 🐞 Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['Bug']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A brief description to explain the bug.

  - type: dropdown
    id: package-version
    attributes:
      label: Package version
      description: The package version used when the bug was encountered.
      options:
        - v6.0.0
        - v6.0.1
        - v6.0.2
        - v6.1.0
        - v6.2.0
        - v6.3.0

    validations:
      required: true

  - type: dropdown
    id: affected-screen
    attributes:
      label: Affected screen
      description: Which screen is affected by this bug.
      options:
        - Incident - Home
        - Incidents
        - Incident - Aggregated loss
        - Incident - Loss matrix
        - Incident - Loss trend
        - I&A - Home
        - Issues
        - Action
        - I&A - Trend analysis
        - I&A - Aging report 
        - KRI - Home
        - KRI library
        - Localized KRI
        - KRI filing
        - KRI monitoring
        - KRI breaches
        - KRI - Top KRIs
        - KRI - Trend analysis
        - Process - Home
        - Processes
        - RCSA - Home
        - Risk library
        - Localized risk
        - Control library
        - Localized control
        - Assessment plans
        - Assessment
        - RCSA - Top risks
        - RCSA - Risk health index
        - RCSA - Top controls
        - RCSA - Control profile

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: Write about what was expected.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: Write about what didn't work.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Steps to take in order to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs & screenshots
      placeholder: Copy paste any relevant logs and screenshots.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: I have checked that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: I have attached relevant logs and/or screenshots.
          required: true
